homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: UTC
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google 

# Cloud
cloud:

# Lovelace
lovelace:
  mode: yaml

automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml


xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_gateway_key 

device_tracker:
  - platform: freebox
    host: !secret freebox
    port: 43567

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XGOU16-if00-port0
  debug: True
  dummy: False

switch:
  platform: rfxtrx
  automatic_add: True

fan:
  - platform: xiaomi_miio
    host: !secret xiaomi
    token: !secret xiaomi_fan_key 

media_player:
  - platform: emby
    host: !secret emby_srv
    api_key: !secret emby_key

influxdb:
  database: telegraf

emulated_hue:

notify:
  - platform: discord
    token: !secret discord

